name: CI

on: push

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Commit-Lint
        uses: wagoid/commitlint-github-action@v5

  buf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v3

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: '1.5.0'

      - name: Buf Linter
        uses: bufbuild/buf-lint-action@v1
        with:
          input: 'bmcapis'

      - name: Buf Breaking Change Check
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'bmcapis'
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main'
